# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170316_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptions',
            name='course_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Courses'),
        ),
    ]
